import time
import pyautogui
from selenium import webdriver
import clipboard

driver = webdriver.Chrome()  # Optional argument, if not specified will search path.
driver.get('https://docs.google.com/spreadsheets/d/1baLk0jJA4g_-Bi5aXnhrBEKAVMNIyGQdRht1Y3Dg2p0/edit#gid=0');
pyautogui.typewrite("andrewaldasoro")
pyautogui.hotkey('enter')
time.sleep(1)
pyautogui.typewrite("Kev-28_abril")
pyautogui.hotkey('enter')
pyautogui.hotkey('ctrl', 't')
pyautogui.typewrite('http://www.canchammx.com/3ntr4d4/');
pyautogui.hotkey('enter')
time.sleep(7)
pyautogui.typewrite("andrewaldasoro")
pyautogui.hotkey('tab')
pyautogui.typewrite("Kev-28_abril")
pyautogui.hotkey('enter')
time.sleep(7)
pyautogui.hotkey('ctrl', 'l')
pyautogui.typewrite('http://www.canchammx.com/wp-admin/user-new.php')
pyautogui.hotkey('enter')
time.sleep(2)
pyautogui.hotkey('ctrl', 'tab')
time.sleep(7)
while True:
    pyautogui.hotkey('ctrl', 'c')
    user = clipboard.paste()
    pyautogui.hotkey('tab')
    pyautogui.hotkey('ctrl', 'c')
    fname = clipboard.paste()
    pyautogui.hotkey('tab')
    pyautogui.hotkey('ctrl', 'c')
    lname = clipboard.paste()
    pyautogui.hotkey('tab')
    pyautogui.hotkey('ctrl', 'c')
    time.sleep(1)
    pyautogui.hotkey('ctrl', 'left')
    pyautogui.hotkey('down')
    pyautogui.hotkey('ctrl', 'tab')
    time.sleep(3)
    pyautogui.click(x=340,y=340)
    pyautogui.typewrite(user)
    pyautogui.hotkey('tab')
    pyautogui.hotkey('ctrl', 'v')
    pyautogui.hotkey('tab')
    pyautogui.typewrite(fname)
    pyautogui.hotkey('tab')
    pyautogui.typewrite(lname)
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('space')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('tab')
    pyautogui.hotkey('enter')
    time.sleep(5)
    pyautogui.hotkey('ctrl', 'l')
    pyautogui.typewrite("http://www.canchammx.com/wp-admin/user-new.php")
    pyautogui.hotkey('enter')
    time.sleep(2)
    pyautogui.hotkey('ctrl', 'tab')
    time.sleep(3)